// Phase 20: Vision Trainer — flash drills. "Count the attackers on this square."
// Random position generated by playing a handful of random moves from start.

import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Chess } from "chess.js";
import { ArrowLeft, Eye, RefreshCw } from "lucide-react";
import { ChessBoard, type SquareHighlight } from "@/components/chess/ChessBoard";
import { useChessGame } from "@/lib/chess/useChessGame";
import { playSound } from "@/lib/chess/sounds";

export const Route = createFileRoute("/trainer/vision")({
  head: () => ({
    meta: [
      { title: "Vision Trainer — ChessMentor" },
      {
        name: "description",
        content:
          "Fast flash drills: count attackers, spot attacked pieces. Builds pattern-recognition speed.",
      },
    ],
  }),
  component: VisionTrainer,
});

function randomPosition(): { fen: string; targetSquare: string; attackers: number } {
  const g = new Chess();
  const plies = 10 + Math.floor(Math.random() * 20);
  for (let i = 0; i < plies; i++) {
    const moves = g.moves();
    if (moves.length === 0) break;
    g.move(moves[Math.floor(Math.random() * moves.length)]);
  }
  const files = "abcdefgh";
  // Pick a piece square of the side to move's OPPONENT (so we count attackers on their piece)
  const board = g.board();
  const target: string[] = [];
  for (let r = 0; r < 8; r++) {
    for (let f = 0; f < 8; f++) {
      const p = board[r][f];
      if (p && p.color !== g.turn()) {
        target.push(files[f] + (8 - r));
      }
    }
  }
  const sq = target[Math.floor(Math.random() * target.length)] ?? "e4";
  // count attackers of side-to-move on that square using chess.js legal-move surface
  const moves = g.moves({ verbose: true }) as Array<{ to: string }>;
  const attackers = moves.filter((m) => m.to === sq).length;
  return { fen: g.fen(), targetSquare: sq, attackers };
}

function VisionTrainer() {
  const game = useChessGame();
  const [state, setState] = useState(() => randomPosition());
  const [score, setScore] = useState(0);
  const [round, setRound] = useState(1);
  const [pick, setPick] = useState<number | null>(null);
  const [reveal, setReveal] = useState(false);

  useEffect(() => {
    game.loadFen(state.fen, { silent: true });
    setPick(null);
    setReveal(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state.fen]);

  const highlights: SquareHighlight[] = [
    { square: state.targetSquare, color: "rgba(217, 119, 6, 0.75)", ring: true },
  ];

  const answer = useCallback(
    (n: number) => {
      if (pick !== null) return;
      setPick(n);
      setReveal(true);
      if (n === state.attackers) {
        setScore((s) => s + 1);
        playSound("check");
      } else {
        playSound("illegal");
      }
    },
    [pick, state.attackers],
  );

  const next = () => {
    setRound((r) => r + 1);
    setState(randomPosition());
  };

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:py-12">
      <Link
        to="/trainer"
        className="mb-4 inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5" /> Trainer hub
      </Link>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <div>
          <ChessBoard game={game} interactive={false} highlights={highlights} />
          <div className="mt-3 font-data text-xs text-muted-foreground">
            Round {round} · Score {score}
          </div>
        </div>
        <aside className="flex flex-col gap-4">
          <div className="app-card">
            <div className="label-caps flex items-center gap-1.5 text-muted-foreground">
              <Eye className="h-3.5 w-3.5 text-primary" /> Vision drill
            </div>
            <h2 className="mt-1 font-display text-lg font-semibold">
              How many attackers on {state.targetSquare}?
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Count all pieces of the side to move that could capture on the
              highlighted square.
            </p>
            <div className="mt-4 grid grid-cols-5 gap-2">
              {[0, 1, 2, 3, 4].map((n) => (
                <button
                  key={n}
                  onClick={() => answer(n)}
                  disabled={pick !== null}
                  className={`grid h-11 place-items-center rounded-md border font-data text-base font-medium transition-colors ${
                    reveal && n === state.attackers
                      ? "border-primary bg-primary text-primary-foreground"
                      : reveal && pick === n
                        ? "border-destructive bg-destructive/10 text-destructive"
                        : "hover:bg-secondary"
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
            {reveal && (
              <p className="mt-3 text-sm">
                {pick === state.attackers ? (
                  <span className="text-primary">Correct — {state.attackers} attackers.</span>
                ) : (
                  <span className="text-destructive">
                    Not quite. There are {state.attackers}.
                  </span>
                )}
              </p>
            )}
            <button
              onClick={next}
              className="mt-4 inline-flex h-10 items-center gap-1.5 rounded-md border bg-background px-3 text-xs font-medium hover:bg-secondary"
            >
              <RefreshCw className="h-3.5 w-3.5" /> Next position
            </button>
          </div>
        </aside>
      </div>
    </div>
  );
}
