/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GuessRouteImport } from './routes/guess'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'

const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GuessRoute = GuessRouteImport.update({
  id: '/guess',
  path: '/guess',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/editor' | '/guess' | '/learn' | '/play' | '/profile' | '/puzzles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/guess' | '/learn' | '/play' | '/profile' | '/puzzles'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/guess'
    | '/learn'
    | '/play'
    | '/profile'
    | '/puzzles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  GuessRoute: typeof GuessRoute
  LearnRoute: typeof LearnRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guess': {
      id: '/guess'
      path: '/guess'
      fullPath: '/guess'
      preLoaderRoute: typeof GuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  GuessRoute: GuessRoute,
  LearnRoute: LearnRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
