/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as StormRouteImport } from './routes/storm'
import { Route as RushRouteImport } from './routes/rush'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GuessRouteImport } from './routes/guess'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CoordinateRouteImport } from './routes/coordinate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerVisionRouteImport } from './routes/trainer.vision'
import { Route as TrainerPracticeRouteImport } from './routes/trainer.practice'
import { Route as TrainerOpeningRouteImport } from './routes/trainer.opening'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StormRoute = StormRouteImport.update({
  id: '/storm',
  path: '/storm',
  getParentRoute: () => rootRouteImport,
} as any)
const RushRoute = RushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GuessRoute = GuessRouteImport.update({
  id: '/guess',
  path: '/guess',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinateRoute = CoordinateRouteImport.update({
  id: '/coordinate',
  path: '/coordinate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerVisionRoute = TrainerVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerPracticeRoute = TrainerPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerOpeningRoute = TrainerOpeningRouteImport.update({
  id: '/opening',
  path: '/opening',
  getParentRoute: () => TrainerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coordinate': typeof CoordinateRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/rush': typeof RushRoute
  '/storm': typeof StormRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainer/opening': typeof TrainerOpeningRoute
  '/trainer/practice': typeof TrainerPracticeRoute
  '/trainer/vision': typeof TrainerVisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coordinate': typeof CoordinateRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/rush': typeof RushRoute
  '/storm': typeof StormRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainer/opening': typeof TrainerOpeningRoute
  '/trainer/practice': typeof TrainerPracticeRoute
  '/trainer/vision': typeof TrainerVisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coordinate': typeof CoordinateRoute
  '/editor': typeof EditorRoute
  '/guess': typeof GuessRoute
  '/learn': typeof LearnRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRoute
  '/rush': typeof RushRoute
  '/storm': typeof StormRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainer/opening': typeof TrainerOpeningRoute
  '/trainer/practice': typeof TrainerPracticeRoute
  '/trainer/vision': typeof TrainerVisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coordinate'
    | '/editor'
    | '/guess'
    | '/learn'
    | '/play'
    | '/practice'
    | '/profile'
    | '/puzzles'
    | '/rush'
    | '/storm'
    | '/trainer'
    | '/trainer/opening'
    | '/trainer/practice'
    | '/trainer/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coordinate'
    | '/editor'
    | '/guess'
    | '/learn'
    | '/play'
    | '/practice'
    | '/profile'
    | '/puzzles'
    | '/rush'
    | '/storm'
    | '/trainer'
    | '/trainer/opening'
    | '/trainer/practice'
    | '/trainer/vision'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coordinate'
    | '/editor'
    | '/guess'
    | '/learn'
    | '/play'
    | '/practice'
    | '/profile'
    | '/puzzles'
    | '/rush'
    | '/storm'
    | '/trainer'
    | '/trainer/opening'
    | '/trainer/practice'
    | '/trainer/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoordinateRoute: typeof CoordinateRoute
  EditorRoute: typeof EditorRoute
  GuessRoute: typeof GuessRoute
  LearnRoute: typeof LearnRoute
  PlayRoute: typeof PlayRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRoute
  RushRoute: typeof RushRoute
  StormRoute: typeof StormRoute
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storm': {
      id: '/storm'
      path: '/storm'
      fullPath: '/storm'
      preLoaderRoute: typeof StormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rush': {
      id: '/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof RushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guess': {
      id: '/guess'
      path: '/guess'
      fullPath: '/guess'
      preLoaderRoute: typeof GuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinate': {
      id: '/coordinate'
      path: '/coordinate'
      fullPath: '/coordinate'
      preLoaderRoute: typeof CoordinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/vision': {
      id: '/trainer/vision'
      path: '/vision'
      fullPath: '/trainer/vision'
      preLoaderRoute: typeof TrainerVisionRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/practice': {
      id: '/trainer/practice'
      path: '/practice'
      fullPath: '/trainer/practice'
      preLoaderRoute: typeof TrainerPracticeRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/opening': {
      id: '/trainer/opening'
      path: '/opening'
      fullPath: '/trainer/opening'
      preLoaderRoute: typeof TrainerOpeningRouteImport
      parentRoute: typeof TrainerRoute
    }
  }
}

interface TrainerRouteChildren {
  TrainerOpeningRoute: typeof TrainerOpeningRoute
  TrainerPracticeRoute: typeof TrainerPracticeRoute
  TrainerVisionRoute: typeof TrainerVisionRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerOpeningRoute: TrainerOpeningRoute,
  TrainerPracticeRoute: TrainerPracticeRoute,
  TrainerVisionRoute: TrainerVisionRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoordinateRoute: CoordinateRoute,
  EditorRoute: EditorRoute,
  GuessRoute: GuessRoute,
  LearnRoute: LearnRoute,
  PlayRoute: PlayRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRoute,
  RushRoute: RushRoute,
  StormRoute: StormRoute,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
